### ISSUE TITLE
Verification fails if root element is <testsuite> and <system-out> presents

### ISSUE THREAD

**Issue by Hsilgos** [weiwei/junitparser#111]
If root element is `<testsuite>` (not `<testsuites>`) and there is `<system-out>` (I think any other also will trigger the issue) then `junitparser verify ...` fails with

```
Traceback (most recent call last):
  File "/Users/.../Library/Python/3.9/bin/junitparser", line 8, in <module>
    sys.exit(main())
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/junitparser/cli.py", line 100, in main
    return verify(
  File "/Users/.../Library/Python/3.9/lib/python/site-packages/junitparser/cli.py", line 33, in verify
    if not case.is_passed and not case.is_skipped:
AttributeError: 'SystemOut' object has no attribute 'is_passed'
```

Basically this is junit test report from `cucumber` test runner.
Simplest example to reproduce the issue:

```
<?xml version="1.0" encoding="UTF-8"?><testsuite tests="783" name="cucumber.runtime.formatter.JUnitFormatter" failures="0" skipped="0" time="1272.267746">
<testcase classname="Test functionality" name="Test name" time="0.641439">
<system-out><![CDATA[Some test.......................passed
]]></system-out>
</testcase>
</testsuite>
```

**Comment by themanifold** [comment]
The problem is that there is no official spec for JUnit XML (which is crazy). If you have a look at https://github.com/testmoapp/junitxml which is probably the most comprehensive unofficial documentation for JUnit XML, you'll see that sometimes tools create XML with `<testsuite>` at the top level, but really, the expectation of junitparser is that the XML that is supplied to it has `<testsuites>` at the upper level.

**Comment by EnricoMi** [comment]
JUnitParser mirrors the allowed JUnit XML schema. The root element can be a `<testsuites>` or a `<testsuite>`. So reading a file may return a `JUnitXml` instance (which reflects `<testsuites>`) or a `TestSuite` instance. Iterating over the former reflects iterating over `<testsuite>` elements, iterating over the latter reflects iterating over `<testcase>` instances. Only `TestCase` class provides the `is_passed`.

**Comment by EnricoMi** [comment]
See #142.
