### ISSUE TITLE
AttributeError: 'Failure' object has no attribute 'is_passed'

### ISSUE THREAD

**Issue by davidfischer-ch** [weiwei/junitparser#140]
Hello,

We face the following exception when parsing one of our JUnit result file with junitparser version 3.2.0:

```python
Traceback (most recent call last):
  File "/home/build/venv/bin/junitparser", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/build/venv/lib/python3.12/site-packages/junitparser/cli.py", line 97, in main
    return verify(
           ^^^^^^^
  File "/home/build/venv/lib/python3.12/site-packages/junitparser/cli.py", line 30, in verify
    if not case.is_passed and not case.is_skipped:
           ^^^^^^^^^^^^^^
AttributeError: 'Failure' object has no attribute 'is_passed'
```

Can you help us fixing the issue?

Thank you.

Content:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Health Check Tests" tests="27" time="0.06" timestamp="2024-10-17T12:32:40+02:00" failures="4"><testcase name="Database connectivity check" time="0"><failure message="Error SQLSTATE[08006] [7] could not translate host name &quot;port=&quot; to address: Name or service not known"/></testcase><testcase name="Database CRUD check" time="0"><failure message="Error Call to a member function exec() on bool"/></testcase><testcase name="HTTP connectivity check with " time="0"><failure message="Error "/></testcase><testcase name="HTTP connectivity check with " time="0"><failure message="Error "/></testcase><testcase name="Check Memory Limit" time="0"/><testcase name="Check post_max_size" time="0"/><testcase name="Check upload_max_filesize" time="0"/><testcase name="Check max_execution_time" time="0"/><testcase name="Check Logs_errors" time="0"/><testcase name="Check php_sapi_name" time="0"/><testcase name="Check current_user" time="0"/><testcase name="Check time zone" time="0"/><testcase name="Check change time limit" time="0"/><testcase name="Check change memory limit" time="0"/><testcase name="Check extensions" time="0"/><testcase name="Check Apache" time="0"/><testcase name="Check Apache version" time="0.03"/><testcase name="Check PHP version" time="0"/><testcase name="Check apache server signature" time="0"/><testcase name="Check apache ServerTokens Prod" time="0"/><testcase name="Check Allowoveride_all" time="0"/><testcase name="Check php_allow_url_fopen" time="0"/><testcase name="Check php_allow_url_include" time="0"/><testcase name="Check php_expose_php" time="0"/><testcase name="Check php_session_save_path" time="0"/><testcase name="Check php_session_use_trans_sid" time="0.03"/><testcase name="Check php_cli" time="0"/></testsuite>
```

**Comment by themanifold** [comment]
Very similar to https://github.com/weiwei/junitparser/issues/111

**Comment by EnricoMi** [comment]
See #142.
