### ISSUE TITLE
New package 2.1.0 is broken

### ISSUE THREAD

**Issue by oren-nonamesecurity** [weiwei/junitparser#68]
```
Traceback (most recent call last):
  File "/usr/local/bin/junitparser", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/junitparser/cli.py", line 51, in main
    args = args or _parser(prog_name=prog_name).parse_args()
  File "/usr/local/lib/python3.7/site-packages/junitparser/cli.py", line 43, in _parser
    "output", help="Merged XML Path, setting to " - " will output console"
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

https://github.com/weiwei/junitparser/commit/78d2599a78ac24014386c17d769081597045cc55#diff-1c9677d820a4b1a30ea84971c65cd4f12d3a49e4e4a0a52ea13b98541a1fef26R43

Line 43 is invalid.

**Comment by weiwei** [comment]
Sorry! Fixed in `2.1.1`.
